In [1]:
import pandas as pd

In [2]:
annot_test = pd.read_csv("/home/harsh/Documents/fau/thesis/thesis-codebase/data/vindr_cxr/annotations/annotations_test.csv")

In [14]:
annot_train = pd.read_csv("/home/harsh/Documents/fau/thesis/thesis-codebase/data/vindr_cxr/annotations/annotations_train.csv")
annot_train.head()

,image_id,rad_id,class_name,x_min,y_min,x_max,y_max
0,000434271f63a053c4128a0ba6352c7f,R2,No finding,NaN,NaN,NaN,NaN
1,000434271f63a053c4128a0ba6352c7f,R3,No finding,NaN,NaN,NaN,NaN
2,000434271f63a053c4128a0ba6352c7f,R6,No finding,NaN,NaN,NaN,NaN
3,00053190460d56c53cc3e57321387478,R11,No finding,NaN,NaN,NaN,NaN
4,00053190460d56c53cc3e57321387478,R2,No finding,NaN,NaN,NaN,NaN

In [3]:
annot_test.head()

,image_id,class_name,x_min,y_min,x_max,y_max
0,e0dc2e79105ad93532484e956ef8a71a,Calcification,1221.560976,661.580417,1343.298780,783.318222
1,e0dc2e79105ad93532484e956ef8a71a,Cardiomegaly,638.695122,1310.848710,1800.737805,1937.982856
2,e0dc2e79105ad93532484e956ef8a71a,ILD,1693.756098,1392.007246,1929.853659,1941.671881
3,e0dc2e79105ad93532484e956ef8a71a,Pneumothorax,399.924053,145.803282,1016.600328,510.138208
4,e0dc2e79105ad93532484e956ef8a71a,Pneumothorax,334.300846,493.762382,453.145487,744.509170

In [4]:
annot_test.shape

(4748, 6)

In [6]:
annot_test.image_id.value_counts()

image_id
ab9dedb9ff4cd9e80dca74505b599105    11
daac34be8b6ca54b0ab1be81733c0d34    11
7858eba2f50d6d515f3ccbbbe9020fa4    11
5118cbe9894006f58312565294e85556    10
e1c35c4312a8aa97233d3b88fb07b033    10
                                    ..
60485f64a1de6c652639c3ab84fcd12f     1
8fc6580091f8d24be3dbd700d4630833     1
c5026a45c2acc85937d1f13c2638f97c     1
c84c9afed6d26c87c30b76ae29ebd290     1
d09ec8573f5c237e56bbeae80f877f18     1
Name: count, Length: 3000, dtype: int64

In [7]:
annot_test[annot_test.image_id == "ab9dedb9ff4cd9e80dca74505b599105"]

,image_id,class_name,x_min,y_min,x_max,y_max
2418,ab9dedb9ff4cd9e80dca74505b599105,Pleural thickening,1135.823714,331.361501,1387.619522,419.490034
2419,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,1477.998645,920.401521,1657.949286,1120.072781
2420,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,1512.149941,1447.780502,1743.376779,1700.864604
2421,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,1441.795000,1197.359484,1733.943880,1444.379676
2422,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,1607.202607,1714.024121,1762.454074,1813.151819
2423,ab9dedb9ff4cd9e80dca74505b599105,Pleural thickening,279.959131,1768.125387,398.180755,1955.966412
2424,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,574.464191,434.711039,813.815767,563.931522
2425,ab9dedb9ff4cd9e80dca74505b599105,Nodule/Mass,462.581164,508.914228,691.484736,709.015364
2426,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,424.546648,748.270553,546.499389,889.735732
2427,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,323.864440,1455.483466,415.222231,1579.358437
2428,ab9dedb9ff4cd9e80dca74505b599105,Pulmonary fibrosis,356.381620,1317.672561,837.945570,1486.452209

In [13]:
annot_test[annot_test.image_id == "ab9dedb9ff4cd9e80dca74505b599105"].class_name.unique()

array(['Pleural thickening', 'Pulmonary fibrosis', 'Nodule/Mass'],
      dtype=object)

In [8]:
img_lbl_test = pd.read_csv("/home/harsh/Documents/fau/thesis/thesis-codebase/data/vindr_cxr/annotations/image_labels_test.csv")

In [9]:
img_lbl_test.head()

,image_id,Aortic enlargement,Atelectasis,Calcification,Cardiomegaly,Clavicle fracture,Consolidation,Edema,Emphysema,Enlarged PA,...,Pneumothorax,Pulmonary fibrosis,Rib fracture,Other lesion,COPD,Lung tumor,Pneumonia,Tuberculosis,Other disease,No finding
0,e0dc2e79105ad93532484e956ef8a71a,0,1,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,1,0
1,0aed23e64ebdea798486056b4f174424,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,aa15cfcfca7605465ca0513902738b95,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
3,665c4a6d2693dc0286d65ab479c9b169,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,42da2c134b53cb5594774d3d29faac59,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
img_lbl_test[img_lbl_test.image_id == "ab9dedb9ff4cd9e80dca74505b599105"]

,image_id,Aortic enlargement,Atelectasis,Calcification,Cardiomegaly,Clavicle fracture,Consolidation,Edema,Emphysema,Enlarged PA,...,Pneumothorax,Pulmonary fibrosis,Rib fracture,Other lesion,COPD,Lung tumor,Pneumonia,Tuberculosis,Other disease,No finding
879,ab9dedb9ff4cd9e80dca74505b599105,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0